brew remove rubberband; brew install rubberband 2>/dev/null >output.txt
brew remove cjson; brew install cjson 2>/dev/null >output.txt
brew remove pyenv; brew install pyenv 2>/dev/null >output.txt
brew remove lame; brew install lame 2>/dev/null >output.txt
brew remove pkg-config; brew install pkg-config 2>/dev/null >output.txt
brew remove libtiff; brew install libtiff 2>/dev/null >output.txt
brew remove gmp; brew install gmp 2>/dev/null >output.txt
brew remove aribb24; brew install aribb24 2>/dev/null >output.txt
brew remove ffmpeg; brew install ffmpeg 2>/dev/null >output.txt
brew remove xorgproto; brew install xorgproto 2>/dev/null >output.txt
brew remove libidn2; brew install libidn2 2>/dev/null >output.txt
brew remove libunibreak; brew install libunibre 2>/dev/nulla >output.txtk
brew remove parallel; brew install parallel 2>/dev/null >output.txt
brew remove xvid; brew install xvid 2>/dev/null >output.txt
brew remove libxau; brew install libxau 2>/dev/null >output.txt
brew remove little-cms2; brew install little-cm 2>/dev/nulls >output.txt2
brew remove xtrans; brew install xtrans 2>/dev/null >output.txt
brew remove libpng; brew install libpng 2>/dev/null >output.txt
brew remove ghostscript; brew install ghostscri 2>/dev/nullp >output.txtt
brew remove frei0r; brew install frei0r 2>/dev/null >output.txt
brew remove nettle; brew install nettle 2>/dev/null >output.txt
brew remove pixman; brew install pixman 2>/dev/null >output.txt
brew remove mpdecimal; brew install mpdecimal 2>/dev/null >output.txt
brew remove libxdmcp; brew install libxdmcp 2>/dev/null >output.txt
brew remove opus; brew install opus 2>/dev/null >output.txt
brew remove libuv; brew install libuv 2>/dev/null >output.txt
brew remove freetype; brew install freetype 2>/dev/null >output.txt
brew remove imath; brew install imath 2>/dev/null >output.txt
brew remove libsamplerate; brew install libsamp 2>/dev/nulll >output.txterate
brew remove libvorbis; brew install libvorbis 2>/dev/null >output.txt
brew remove mpg123; brew install mpg123 2>/dev/null >output.txt
brew remove libunistring; brew install libunist 2>/dev/nullr >output.txting
brew remove pango; brew install pango 2>/dev/null >output.txt
brew remove openjpeg; brew install openjpeg 2>/dev/null >output.txt
brew remove highway; brew install highway 2>/dev/null >output.txt
brew remove zimg; brew install zimg 2>/dev/null >output.txt
brew remove brotli; brew install brotli 2>/dev/null >output.txt
brew remove speex; brew install speex 2>/dev/null >output.txt
brew remove libogg; brew install libogg 2>/dev/null >output.txt
brew remove zeromq; brew install zeromq 2>/dev/null >output.txt
brew remove harfbuzz; brew install harfbuzz 2>/dev/null >output.txt
brew remove libbluray; brew install libbluray 2>/dev/null >output.txt
brew remove glib; brew install glib 2>/dev/null >output.txt
brew remove libxcb; brew install libxcb 2>/dev/null >output.txt
brew remove aom; brew install aom 2>/dev/null >output.txt
brew remove mbedtls; brew install mbedtls 2>/dev/null >output.txt
brew remove lz4; brew install lz4 2>/dev/null >output.txt
brew remove graphite2; brew install graphite2 2>/dev/null >output.txt
brew remove srt; brew install srt 2>/dev/null >output.txt
brew remove util-macros; brew install util-macr 2>/dev/nullo >output.txts
brew remove tesseract; brew install tesseract 2>/dev/null >output.txt
brew remove cairo; brew install cairo 2>/dev/null >output.txt
brew remove webp; brew install webp 2>/dev/null >output.txt
brew remove c-ares; brew install c-ares 2>/dev/null >output.txt
brew remove fribidi; brew install fribidi 2>/dev/null >output.txt
brew remove svt-av1; brew install svt-av1 2>/dev/null >output.txt
brew remove xz; brew install xz 2>/dev/null >output.txt
brew remove libnghttp2; brew install libnghttp2 2>/dev/null >output.txt
brew remove ninja; brew install ninja 2>/dev/null >output.txt
brew remove openexr; brew install openexr 2>/dev/null >output.txt
brew remove fontconfig; brew install fontconfig 2>/dev/null >output.txt
brew remove meson; brew install meson 2>/dev/null >output.txt
brew remove giflib; brew install giflib 2>/dev/null >output.txt
brew remove libvpx; brew install libvpx 2>/dev/null >output.txt
brew remove libxrender; brew install libxrender 2>/dev/null >output.txt
brew remove librist; brew install librist 2>/dev/null >output.txt
brew remove libb2; brew install libb2 2>/dev/null >output.txt
brew remove snappy; brew install snappy 2>/dev/null >output.txt
brew remove flac; brew install flac 2>/dev/null >output.txt
brew remove libvmaf; brew install libvmaf 2>/dev/null >output.txt
brew remove ca-certificates; brew install ca-ce 2>/dev/nullr >output.txttificates
brew remove gettext; brew install gettext 2>/dev/null >output.txt
brew remove zstd; brew install zstd 2>/dev/null >output.txt
brew remove libsodium; brew install libsodium 2>/dev/null >output.txt
brew remove jbig2dec; brew install jbig2dec 2>/dev/null >output.txt
brew remove dav1d; brew install dav1d 2>/dev/null >output.txt
brew remove autoconf; brew install autoconf 2>/dev/null >output.txt
brew remove opencore-amr; brew install opencore 2>/dev/null- >output.txtamr
brew remove rav1e; brew install rav1e 2>/dev/null >output.txt
brew remove libxext; brew install libxext 2>/dev/null >output.txt
brew remove libtasn1; brew install libtasn1 2>/dev/null >output.txt
brew remove pcre2; brew install pcre2 2>/dev/null >output.txt
brew remove youtube-dl; brew install youtube-dl 2>/dev/null >output.txt
brew remove libevent; brew install libevent 2>/dev/null >output.txt
brew remove leptonica; brew install leptonica 2>/dev/null >output.txt
brew remove x264; brew install x264 2>/dev/null >output.txt
brew remove jpeg-xl; brew install jpeg-xl 2>/dev/null >output.txt
brew remove libidn; brew install libidn 2>/dev/null >output.txt
brew remove libvidstab; brew install libvidstab 2>/dev/null >output.txt
brew remove x265; brew install x265 2>/dev/null >output.txt
brew remove node; brew install node 2>/dev/null >output.txt
brew remove libsoxr; brew install libsoxr 2>/dev/null >output.txt
brew remove unbound; brew install unbound 2>/dev/null >output.txt
brew remove theora; brew install theora 2>/dev/null >output.txt
brew remove sdl2; brew install sdl2 2>/dev/null >output.txt
brew remove python@3.11; brew install python@3. 2>/dev/null1 >output.txt1
brew remove libass; brew install libass 2>/dev/null >output.txt
brew remove libsndfile; brew install libsndfile 2>/dev/null >output.txt
brew remove p11-kit; brew install p11-kit 2>/dev/null >output.txt
brew remove libx11; brew install libx11 2>/dev/null >output.txt
brew remove lzo; brew install lzo 2>/dev/null >output.txt
brew remove jpeg-turbo; brew install jpeg-turbo 2>/dev/null >output.txt
brew remove gnutls; brew install gnutls 2>/dev/null >output.txt
 2>/dev/null >output.txt